/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FernandezProject;


/**
 *
 * @author JOEBELL ARABIT
 */
public class showR extends javax.swing.JFrame {

    /**
     * Creates new form showR
     */
    public showR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tuesdayBtn = new javax.swing.JButton();
        mondayBtn = new javax.swing.JButton();
        wednesdayBtn = new javax.swing.JButton();
        thursdayBtn = new javax.swing.JButton();
        fridayBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tuesdayBtn.setBackground(new java.awt.Color(102, 102, 102));
        tuesdayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tuesdayBtn.setForeground(new java.awt.Color(255, 255, 255));
        tuesdayBtn.setText("Tuesday");
        tuesdayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tuesdayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tuesdayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, 110));

        mondayBtn.setBackground(new java.awt.Color(102, 102, 102));
        mondayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mondayBtn.setForeground(new java.awt.Color(255, 255, 255));
        mondayBtn.setText("Monday");
        mondayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mondayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 90));

        wednesdayBtn.setBackground(new java.awt.Color(102, 102, 102));
        wednesdayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        wednesdayBtn.setForeground(new java.awt.Color(255, 255, 255));
        wednesdayBtn.setText("Wednesday");
        wednesdayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(wednesdayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 130, 90));

        thursdayBtn.setBackground(new java.awt.Color(102, 102, 102));
        thursdayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        thursdayBtn.setForeground(new java.awt.Color(255, 255, 255));
        thursdayBtn.setText("Thursday");
        thursdayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thursdayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(thursdayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 140, 80));

        fridayBtn.setBackground(new java.awt.Color(102, 102, 102));
        fridayBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fridayBtn.setForeground(new java.awt.Color(255, 255, 255));
        fridayBtn.setText("Friday");
        fridayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fridayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(fridayBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 130, 80));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("< Back");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 511, 290));

        setSize(new java.awt.Dimension(511, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mondayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayBtnActionPerformed
        this.dispose();
        Monday show = new Monday();
        show.setVisible(true);
    }//GEN-LAST:event_mondayBtnActionPerformed

    private void tuesdayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tuesdayBtnActionPerformed
        this.dispose();
        Tuesday show = new Tuesday();
        show.setVisible(true);
    }//GEN-LAST:event_tuesdayBtnActionPerformed

    private void wednesdayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayBtnActionPerformed
       this.dispose();
        Wednesday show = new Wednesday();
        show.setVisible(true);
    }//GEN-LAST:event_wednesdayBtnActionPerformed

    private void thursdayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thursdayBtnActionPerformed
        this.dispose();
        Thursday show = new Thursday();
        show.setVisible(true);
    }//GEN-LAST:event_thursdayBtnActionPerformed

    private void fridayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fridayBtnActionPerformed
        this.dispose();
        Friday show = new Friday();
        show.setVisible(true);
    }//GEN-LAST:event_fridayBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        StudentList show = new StudentList();
        show.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fridayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mondayBtn;
    private javax.swing.JButton thursdayBtn;
    private javax.swing.JButton tuesdayBtn;
    private javax.swing.JButton wednesdayBtn;
    // End of variables declaration//GEN-END:variables
}
